version: "3.8"
services:
  api:
    image: noxus-docker.jar:latest
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: postgres:alpine
    container_name: dev-postgres-noxus
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ds_noxus
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: