spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ds_noxus
    username: postgres
    password: 12345678
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update