spring:
  datasource:
    url: jdbc:postgresql://database:5432/ds_noxus
    username: postgres
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update