spring:
  datasource:
    url: jdbc:postgresql://divina-sopa-noxus.cpl462gcizal.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: 12345678
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update