spring:
  profiles:
    active: ${APP_PROFILE:prod}
  jpa:
    open-in-view: false
  main:
    allow-circular-references: true

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

jwt:
  security:
    token: doideira-maluco